/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_programacion2;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author KATHERINE
 */
public class principal_exam extends javax.swing.JFrame {
 String [] titulos={"NOMBRE"};
    DefaultTableModel dtm=new DefaultTableModel(null,titulos);
    Object [] modelo =new Object[1];
    
    String [] titulos2={"autor","publicacion"};
    DefaultTableModel dtm2=new DefaultTableModel(null,titulos2);
    Object [] modelo2 =new Object[2];
    
    DefaultTableModel dtm3=new DefaultTableModel(null,titulos);
    Object [] modelo3 =new Object[1];
    
    
        
   
    /**
     * Creates new form principal_exam
     */
    public principal_exam() {
        initComponents();
        
        nombre.setEditable(false);
        correo.setEditable(false);
        fecha.setEditable(false);
        usuarui1.setEditable(false);
        contraseña.setEditable(false);
        new_fecha.setEnabled(false);
        
        
        
        
         usuario.add(new usuario_administrador("katherine Fiallos","katherine Fiallos", "kathe_mantunez@hotmail.com",
                    (Date)js_fecha.getValue(), "kathe", "123", lb_imagen.getIcon()));
              
              
              
              
              usuario_administrador x2=new usuario_administrador("katherine Fiallos","katherine Fiallos", "kathe_mantunez@hotmail.com",
                    (Date)js_fecha.getValue(), "kathe", "123", lb_imagen.getIcon());
            
            
            admin_usuario_administrador ad1=new admin_usuario_administrador("./usuario_administrador.cbm");
            ad1.cargarArchivo();
            ad1.set_usuario_administrador(x2);
            ad1.escribirArchivo();
            System.out.println(ad1.getListas_usuario_administrador());
            
            
            
            tabla1.setModel(dtm);
           
            
           
    
    }
    
   
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_contraseña_login = new javax.swing.JTextField();
        tf_usuario_login = new javax.swing.JTextField();
        loging = new javax.swing.JButton();
        USUARIO = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_imagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        agregar_usuario = new javax.swing.JButton();
        tf_nombre = new javax.swing.JTextField();
        tf_usuario = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        tf_contraseña = new javax.swing.JTextField();
        rb_usuario_normal = new javax.swing.JRadioButton();
        rb_usuario_admin = new javax.swing.JRadioButton();
        js_fecha = new javax.swing.JSpinner();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        menu_administrador = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tax2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        bloquear_normal = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        bloquear_publicaciones = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_normal = new javax.swing.JDialog();
        tab = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texta = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bt_problema = new javax.swing.JRadioButton();
        bt_repuestas = new javax.swing.JRadioButton();
        bt_comentario = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        bt_publico = new javax.swing.JRadioButton();
        bt_privado = new javax.swing.JRadioButton();
        bt_amigos = new javax.swing.JRadioButton();
        js_categoria = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        js_respuestas = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_comentario = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        bt_cerrado = new javax.swing.JRadioButton();
        bt_abierto = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_p = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        usuarui1 = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        new_fecha = new javax.swing.JSpinner();
        jButton9 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jButton6 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabla_usuarios = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel8.setText("usuario");

        jLabel9.setText("contraseña");

        loging.setText("login");
        loging.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login.getContentPane());
        login.getContentPane().setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(56, 56, 56)
                                .addComponent(tf_contraseña_login, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(loging, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                    .addContainerGap(171, Short.MAX_VALUE)
                    .addComponent(tf_usuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(69, 69, 69)))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel8)
                .addGap(55, 55, 55)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_contraseña_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(loging, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(tf_usuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(287, Short.MAX_VALUE)))
        );

        jLabel1.setText("USUARIOS");

        jLabel2.setText("Nombre Completo");

        jLabel3.setText("Correo");

        jLabel4.setText("Fecha");

        jLabel5.setText("Usuario");

        jLabel6.setText("Contraseña");

        jLabel7.setText("Imagen");

        jButton1.setText("cargar imagen");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        agregar_usuario.setText("Agregar");
        agregar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_usuarioMouseClicked(evt);
            }
        });

        buttonGroup1.add(rb_usuario_normal);
        rb_usuario_normal.setSelected(true);
        rb_usuario_normal.setText("Usuario normal");

        buttonGroup1.add(rb_usuario_admin);
        rb_usuario_admin.setText("Usuario administrador");

        js_fecha.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout USUARIOLayout = new javax.swing.GroupLayout(USUARIO.getContentPane());
        USUARIO.getContentPane().setLayout(USUARIOLayout);
        USUARIOLayout.setHorizontalGroup(
            USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USUARIOLayout.createSequentialGroup()
                .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(USUARIOLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(agregar_usuario))
                    .addGroup(USUARIOLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(USUARIOLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jButton1)
                    .addComponent(rb_usuario_normal))
                .addGap(23, 23, 23)
                .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(USUARIOLayout.createSequentialGroup()
                        .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(USUARIOLayout.createSequentialGroup()
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(USUARIOLayout.createSequentialGroup()
                                .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))
                    .addGroup(USUARIOLayout.createSequentialGroup()
                        .addComponent(lb_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(USUARIOLayout.createSequentialGroup()
                        .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(js_fecha)
                            .addComponent(rb_usuario_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        USUARIOLayout.setVerticalGroup(
            USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USUARIOLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(USUARIOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(USUARIOLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(js_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(USUARIOLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(USUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_usuario_normal)
                            .addComponent(rb_usuario_admin))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(USUARIOLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lb_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(agregar_usuario)
                .addGap(43, 43, 43))
        );

        jButton2.setText("jButton2");

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        tax2.setColumns(20);
        tax2.setRows(5);
        jScrollPane2.setViewportView(tax2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("principal", jPanel2);

        jLabel13.setText("Usuarios");

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabla1);

        bloquear_normal.setText("bloquedar");
        bloquear_normal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloquear_normalMouseClicked(evt);
            }
        });
        bloquear_normal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                bloquear_normalComponentHidden(evt);
            }
        });

        jLabel10.setText("Publicaciones");

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabla2);

        bloquear_publicaciones.setText("bloquedar");
        bloquear_publicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloquear_publicacionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bloquear_publicaciones)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(bloquear_normal)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bloquear_normal)
                .addGap(51, 51, 51)
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bloquear_publicaciones)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Usuario / Publicaciones", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab3", jPanel3);

        jMenu3.setText("Usuario administrador");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("abrir");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("guardar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("about");
        jMenu3.add(jMenuItem6);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        menu_administrador.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout menu_administradorLayout = new javax.swing.GroupLayout(menu_administrador.getContentPane());
        menu_administrador.getContentPane().setLayout(menu_administradorLayout);
        menu_administradorLayout.setHorizontalGroup(
            menu_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_administradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        menu_administradorLayout.setVerticalGroup(
            menu_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_administradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        tab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabStateChanged(evt);
            }
        });

        texta.setColumns(20);
        texta.setRows(5);
        jScrollPane1.setViewportView(texta);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        tab.addTab("principal", jPanel4);

        jLabel11.setText("hacer publicacion");

        buttonGroup3.add(bt_problema);
        bt_problema.setText("problemas");

        buttonGroup3.add(bt_repuestas);
        bt_repuestas.setText("respuestas");

        buttonGroup3.add(bt_comentario);
        bt_comentario.setText("comentarios");

        jLabel12.setText("ID");

        jLabel14.setText("mensaje");

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane5.setViewportView(ta_mensaje);

        buttonGroup2.add(bt_publico);
        bt_publico.setText("publico");

        buttonGroup2.add(bt_privado);
        bt_privado.setText("privado");

        buttonGroup2.add(bt_amigos);
        bt_amigos.setText("amigos");

        js_categoria.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));

        jLabel15.setText("estado");

        jLabel16.setText("categoria");

        js_respuestas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel17.setText("calificacion general");

        ta_comentario.setColumns(20);
        ta_comentario.setRows(5);
        jScrollPane6.setViewportView(ta_comentario);

        jButton3.setText("PUBLICAR");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        buttonGroup4.add(bt_cerrado);
        bt_cerrado.setSelected(true);
        bt_cerrado.setText("cerrado");

        buttonGroup4.add(bt_abierto);
        bt_abierto.setText("abierto");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_id)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_publico)
                            .addComponent(bt_privado)
                            .addComponent(bt_amigos)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(bt_problema)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(js_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(bt_cerrado)
                                        .addGap(18, 18, 18)
                                        .addComponent(bt_abierto)))))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_repuestas)
                            .addComponent(js_respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_comentario))))
                .addGap(46, 46, 46))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_publico)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(bt_privado)
                        .addGap(46, 46, 46)
                        .addComponent(bt_amigos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_problema)
                    .addComponent(bt_repuestas)
                    .addComponent(bt_comentario))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(js_respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_cerrado)
                            .addComponent(bt_abierto))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addGap(40, 40, 40))
        );

        tab.addTab("hacer publicaciones", jPanel5);

        jl_p.setModel(new DefaultListModel()
        );
        jScrollPane7.setViewportView(jl_p);

        jButton4.setText("ver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        tab.addTab("ver publicaciones", jPanel6);

        jButton7.setText("modificar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("eliminar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jLabel19.setText("nombre");

        jLabel20.setText("correo");

        jLabel21.setText("fecha de nacimiento");

        jLabel22.setText("usuario");

        jLabel23.setText("contraseña");

        new_fecha.setModel(new javax.swing.SpinnerDateModel());

        jButton9.setText("actualizar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(new_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(322, 322, 322))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel22)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addGap(0, 0, 0)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarui1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(195, 195, 195))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usuarui1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel21))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(new_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(30, 30, 30)
                .addComponent(jButton9)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        tab.addTab("info personal", jPanel7);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("solicitudes");
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane8.setViewportView(arbol);

        jButton6.setText("cargar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(tabla_usuarios);

        jLabel24.setText("usuarios");

        jButton10.setText("agregar a mis amigos");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(395, 395, 395))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        tab.addTab("solicitud", jPanel8);

        jMenu5.setText("USUARIO NORMAL");

        jMenuItem7.setText("abrir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("salir");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem10.setText("about");
        jMenu5.add(jMenuItem10);

        jMenuBar3.add(jMenu5);

        jMenu6.setText("PUBLICACIONES");

        jMenuItem9.setText("hacer publicacion");
        jMenu6.add(jMenuItem9);

        jMenuBar3.add(jMenu6);

        menu_normal.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout menu_normalLayout = new javax.swing.GroupLayout(menu_normal.getContentPane());
        menu_normal.getContentPane().setLayout(menu_normalLayout);
        menu_normalLayout.setHorizontalGroup(
            menu_normalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_normalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        menu_normalLayout.setVerticalGroup(
            menu_normalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_normalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("StackOverFlow ");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Iniciar Sesión");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenu2.setText("Registro");

        jMenuItem1.setText("Usuario normal/administrador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
           USUARIO.setModal(true);
        USUARIO.pack();
        USUARIO.setLocationRelativeTo(this);
        USUARIO.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        JFileChooser fc=new JFileChooser();
        
        FileFilter filtro =new FileNameExtensionFilter("Imagenes", "png","jpg","jpeg","gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op=fc.showOpenDialog(USUARIO);
        if(op==JFileChooser.APPROVE_OPTION){
            archivo=fc.getSelectedFile();
            Image img=Toolkit.getDefaultToolkit().createImage(
                        archivo.getPath()).getScaledInstance(100, 100, 0);
            this.lb_imagen.setIcon(new ImageIcon(img));
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void agregar_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_usuarioMouseClicked
        // TODO add your handling code here:
      
        
        if(rb_usuario_normal.isSelected()){
            //usuario normal
            //          String nombre2, String nombre, String correo, Date fecha, String usuario, String contraseña, Icon imagen  //

            usuario.add(new usuario_normal(tf_nombre.getText(), tf_nombre.getText(), tf_correo.getText(),
                    (Date)js_fecha.getValue(), tf_usuario.getText(), tf_contraseña.getText(), lb_imagen.getIcon()));
            
            usuario_normal un=new usuario_normal(tf_nombre.getText(), tf_nombre.getText(), tf_correo.getText(),
                    (Date)js_fecha.getValue(), tf_usuario.getText(), tf_contraseña.getText(), lb_imagen.getIcon());
            
            
            admin_usuario_normal ad=new admin_usuario_normal("./usuario_normal.cbm");
            ad.cargarArchivo();
            ad.set_usuario_comun(un);
            ad.escribirArchivo();
            
            JOptionPane.showMessageDialog(USUARIO, "usuario normal registrado exitosamente");
            tf_nombre.setText("");
            tf_correo.setText("");
            tf_usuario.setText("");
            tf_contraseña.setText("");
            lb_imagen.setIcon(null);
            
            
        }else{
            //USUARIO ADMINISTRADOR
            //String nombre2, String nombre, String correo, Date fecha, String usuario, String contraseña, Icon imagen
              usuario.add(new usuario_administrador(tf_nombre.getText(), tf_nombre.getText(), tf_correo.getText(),
                    (Date)js_fecha.getValue(), tf_usuario.getText(), tf_contraseña.getText(), lb_imagen.getIcon()));
              
              
              
              
              usuario_administrador x=new usuario_administrador(tf_nombre.getText(), tf_nombre.getText(), tf_correo.getText(),
                    (Date)js_fecha.getValue(), tf_usuario.getText(), tf_contraseña.getText(), lb_imagen.getIcon());
            
            
            admin_usuario_administrador ad=new admin_usuario_administrador("./usuario_administrador.cbm");
            ad.cargarArchivo();
            ad.set_usuario_administrador(x);
            ad.escribirArchivo();
            
            JOptionPane.showMessageDialog(USUARIO, "usuario administrador registrado exitosamente");
              
              
              
              
              
              tf_nombre.setText("");
            tf_correo.setText("");
            tf_usuario.setText("");
            tf_contraseña.setText("");
             lb_imagen.setIcon(null);
        }
    }//GEN-LAST:event_agregar_usuarioMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         login.setModal(true);
        login.pack();
        login.setLocationRelativeTo(this);
        login.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void logingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logingMouseClicked
        // TODO add your handling code here:
        admin_usuario_normal ap=new admin_usuario_normal("./usuario_normal.cbm");
        ap.cargarArchivo();
        admin_usuario_administrador ap2=new admin_usuario_administrador("./usuario_administrador.cbm");
        ap2.cargarArchivo();
//         DefaultTableModel modelo1 = (DefaultTableModel) tabla_usuario.getModel();
            for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
               if(tf_usuario_login.getText().equals(ap.getListas_usuario_normal().get(i).getUsuario()) &&
                    tf_contraseña_login.getText().equals(ap.getListas_usuario_normal().get(i).getContraseña())){
                     JOptionPane.showMessageDialog(USUARIO, "usuario normal");
                     
                     
                     usuario_normal_actual=(usuario_normal)ap.getListas_usuario_normal().get(i);
                     nombre.setText(ap.getListas_usuario_normal().get(i).getNombre());
                     correo.setText(ap.getListas_usuario_normal().get(i).getCorreo());
                     fecha.setText(ap.getListas_usuario_normal().get(i).getFecha().toString());
                     usuarui1.setText(ap.getListas_usuario_normal().get(i).getUsuario());
                     contraseña.setText(ap.getListas_usuario_normal().get(i).getContraseña());
                         
                      menu_normal.setModal(true);
                        menu_normal.pack();
                        menu_normal.setLocationRelativeTo(this);
                        menu_normal.setVisible(true);
                     
                    
                     
                     
                     tf_contraseña_login.setText("");
                     tf_usuario_login.setText("");
                     
                     
//                     modelo1.setRowCount(0);
//                    String[] newrow = {ap.getListas_usuario_normal().get(i).getNombre(), ap.getListas_usuario_normal().get(i).getCorreo(),
//                        ap.getListas_usuario_normal().get(i).getFecha().toString(), ap.getListas_usuario_normal().get(i).getUsuario(),
//                        ap.getListas_usuario_normal().get(i).getContraseña()};
//                    modelo1.addRow(newrow);
                    
//                
//                 }
            }
            }
            
            for (int i = 0; i < ap2.getListas_usuario_administrador().size(); i++) {
               if(tf_usuario_login.getText().equals(ap2.getListas_usuario_administrador().get(i).getUsuario()) &&
                    tf_contraseña_login.getText().equals(ap2.getListas_usuario_administrador().get(i).getContraseña())){
                     JOptionPane.showMessageDialog(USUARIO, "usuario administrador");
                      menu_administrador.setModal(true);
                        menu_administrador.pack();
                        menu_administrador.setLocationRelativeTo(this);
                        menu_administrador.setVisible(true);
                     
                     usuario_admin_actual=(usuario_administrador)ap2.getListas_usuario_administrador().get(i);
                     
                     
                     tf_contraseña_login.setText("");
                     tf_usuario_login.setText("");
//                
            
//                 }
            }
            }
        
        
        
    }//GEN-LAST:event_logingMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
        //guardar
        admin_usuario_administrador ap=new admin_usuario_administrador("./administrador.cbm");
        ap.cargarArchivo();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        // TODO add your handling code here:
        
        admin_usuario_normal ap=new admin_usuario_normal("./usuario_normal.cbm");
        ap.cargarArchivo();
        dtm.setRowCount(0);
        for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
            modelo[0]=ap.getListas_usuario_normal().get(i);
            
         dtm.addRow(modelo);
         
         tabla1.setModel(dtm);
        }
        
        
        admin_comentarios c=new admin_comentarios("./comentarios.cbm");
        c.cargarArchivo();
        dtm2.setRowCount(0);
        for (int i = 0; i <c.getListas_comentarios().size(); i++) {
            modelo2[0]=ap.getListas_usuario_normal().get(i);
            
         dtm2.addRow(modelo2);
         
         tabla2.setModel(dtm2);
        }
        
        
        
        admin_problemas c2=new admin_problemas("./problemas.cbm");
        c2.cargarArchivo();
        dtm2.setRowCount(0);
        for (int i = 0; i <c2.getListas_problemas().size(); i++) {
            modelo2[0]=c2.getListas_problemas().get(i);
            
         dtm2.addRow(modelo2);
         
         tabla2.setModel(dtm2);
        }
        
        
        admin_respuestas c3=new admin_respuestas("./respuestas.cbm");
        c3.cargarArchivo();
        dtm2.setRowCount(0);
        for (int i = 0; i <c3.getListas_respuestas().size(); i++) {
            modelo2[0]=c3.getListas_respuestas().get(i);
            
         dtm2.addRow(modelo2);
         
         tabla2.setModel(dtm2);
        }
        

    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void bloquear_normalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloquear_normalMouseClicked
        // TODO add your handling code here:
        admin_usuario_administrador ad=new admin_usuario_administrador("./usuario_administrador.cbm");
            ad.cargarArchivo();
             admin_usuario_normal ap=new admin_usuario_normal("./usuario_normal.cbm");
        ap.cargarArchivo();
        int filaselect=tabla1.getSelectedRow();
        
        if(filaselect>=0){
//            for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
//                if(i==filaselect){
//                    ad.getListas_usuario_administrador().get(1).setUsuario_normal_bloqueado(ap.getListas_usuario_normal().get(i));
//                    System.out.println("bloquedo:"+ap.getListas_usuario_normal().get(i));
//                }
//            }
            
        }else{
            JOptionPane.showMessageDialog(menu_administrador, "FILA no seleccionada");
        }
    }//GEN-LAST:event_bloquear_normalMouseClicked

    private void bloquear_publicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloquear_publicacionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bloquear_publicacionesMouseClicked

    private void bloquear_normalComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bloquear_normalComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_bloquear_normalComponentHidden

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        menu_administrador.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        //Abrir archivo bianrio
          File fichero=null;
        FileReader fr=null;
        BufferedReader br=null;
        texta.setText("");
        try {
            JFileChooser jfc=new JFileChooser("./");
            //JFileChooser jfc=new JFileChooser("./");//Desde el directorio del proyecto
            FileNameExtensionFilter filtro= new FileNameExtensionFilter("Archivos de texto","cbm");
            
            
         
            jfc.setFileFilter(filtro);
            //----------------------
            int seleccion=jfc.showOpenDialog(this);//Abrir archivo
            if(seleccion==JFileChooser.APPROVE_OPTION){
                fichero=jfc.getSelectedFile();
                fr=new FileReader(fichero);
                
                br=new BufferedReader(fr);
                String linea;
                texta.setText("");
                while((linea=br.readLine())!= null){
                 
                    texta.append(linea);
                    texta.append("\n");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        menu_normal.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
          File fichero=null;
        FileReader fr=null;
        BufferedReader br=null;
        tax2.setText("");
        try {
            JFileChooser jfc=new JFileChooser("./");
            //JFileChooser jfc=new JFileChooser("./");//Desde el directorio del proyecto
            FileNameExtensionFilter filtro= new FileNameExtensionFilter("Archivos de texto","cbm");
            
            
         
            jfc.setFileFilter(filtro);
            //----------------------
            int seleccion=jfc.showOpenDialog(this);//Abrir archivo
            if(seleccion==JFileChooser.APPROVE_OPTION){
                fichero=jfc.getSelectedFile();
                fr=new FileReader(fichero);
                
                br=new BufferedReader(fr);
                String linea;
                tax2.setText("");
                while((linea=br.readLine())!= null){
                 
                    tax2.append(linea);
                    tax2.append("\n");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        admin_usuario_normal ap=new admin_usuario_normal("./usuario_normal.cbm");
        ap.cargarArchivo();
        //String ID, Mensajes mensajes, usuario_normal usuario_autor, String privacidad, Date fecha
        String p="";
        String estado;
        Date f=new Date();
        if(bt_problema.isSelected()){
            if(bt_privado.isSelected()){
                p="privado";
            }else{
                if(bt_publico.isSelected()){
                    p="publico";
                }else{
                    p="amigos";
                }
            
            }
        
        if(bt_cerrado.isSelected()){
            estado="cerrado";
        }else{
            estado="abierto";
        }
            
            
            
            //String estado, int categoria, String ID, String mensajes, usuario_normal usuario_autor, String privacidad, Date fecha
        publicacion.add(new problemas(estado, Integer.parseInt(js_categoria.getValue().toString()), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f));
                
        problemas publi =new problemas(estado, Integer.parseInt(js_categoria.getValue().toString()), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f);
         admin_problemas ad=new admin_problemas("./problemas.cbm");
         ad.cargarArchivo();
                 
         ad.set_problemas(publi);
         ad.escribirArchivo();
         for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
            if(ap.getListas_usuario_normal().get(i).equals(usuario_normal_actual)){
                ap.getListas_usuario_normal().get(i).setPublicaciones((publicaciones)publi);
            }
         
         
         
         
         
        }
         
         
         JOptionPane.showMessageDialog(menu_normal, "problema publicado");
        }
        if(bt_comentario.isSelected()){
            
               if(bt_privado.isSelected()){
                p="privado";
            }else{
                if(bt_publico.isSelected()){
                    p="publico";
                }else{
                    p="amigos";
                }
            
            }
        
       
            
            
            
            //String estado, int categoria, String ID, String mensajes, usuario_normal usuario_autor, String privacidad, Date fecha
        publicacion.add(new comentarios(ta_comentario.getText(), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f));
                
        comentarios comen =new comentarios(ta_comentario.getText(), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f);
            admin_comentarios ad1=new admin_comentarios("./comentarios.cbm");
            
            
         ad1.cargarArchivo();
                 
         ad1.set_comentarios(comen);
         
         ad1.escribirArchivo();
            
            for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
            if(ap.getListas_usuario_normal().get(i).equals(usuario_normal_actual)){
                ap.getListas_usuario_normal().get(i).setPublicaciones((publicaciones)comen);
            }
            
            
        }
            
            JOptionPane.showMessageDialog(menu_normal, "comentario publicado");
        }
        if(bt_repuestas.isSelected()){
            //int calificacion_general, String ID, String mensajes, usuario_normal usuario_autor, String privacidad, Date fecha
            
            
               if(bt_privado.isSelected()){
                p="privado";
            }else{
                if(bt_publico.isSelected()){
                    p="publico";
                }else{
                    p="amigos";
                }
            
            }
        
       
            
            
            
            //String estado, int categoria, String ID, String mensajes, usuario_normal usuario_autor, String privacidad, Date fecha
        publicacion.add(new Respuestas(Integer.parseInt(js_respuestas.getValue().toString()), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f));
                
        Respuestas res =new Respuestas(Integer.parseInt(js_respuestas.getValue().toString()), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f);
            admin_respuestas ad2=new admin_respuestas("./respuestas.cbm");
            
            
         ad2.cargarArchivo();
                 
         ad2.set_respuestas(res);
         
         ad2.escribirArchivo();
            
            for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
            if(ap.getListas_usuario_normal().get(i).equals(usuario_normal_actual)){
                ap.getListas_usuario_normal().get(i).setPublicaciones((publicaciones)res);
            }
        }
            
            JOptionPane.showMessageDialog(menu_normal, "respuestas publicado");
            
        }
        
//        
//        
//        
//        
//        
        
//        
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model=(DefaultListModel)jl_p.getModel();
        model.removeAllElements();
        jl_p.setModel(model);
        admin_comentarios a=new admin_comentarios("./comentarios.cbm");
        a.cargarArchivo();
          admin_respuestas b=new admin_respuestas("./respuestas.cbm");
         b.cargarArchivo();
         admin_problemas c=new admin_problemas("./problemas.cbm");
         c.cargarArchivo();
         
         
         
         
         
         for (int i = 0; i < a.getListas_comentarios().size(); i++) {
             model.addElement(a.getListas_comentarios().get(i));
            
        }
         for (int i = 0; i < b.getListas_respuestas().size(); i++) {
             model.addElement(b.getListas_respuestas().get(i));
            
        }
         for (int i = 0; i < c.getListas_problemas().size(); i++) {
             model.addElement(c.getListas_problemas().get(i));
            
        }
         
         jl_p.setModel(model);
         
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabStateChanged
        admin_usuario_normal ap=new admin_usuario_normal("./usuario_normal.cbm");
        ap.cargarArchivo();
        
        if(tab.getSelectedIndex()==4){
        DefaultTreeModel modelo_arbol=(DefaultTreeModel)arbol.getModel();
        DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modelo_arbol.getRoot();
        raiz.removeAllChildren();
        modelo_arbol.reload();
         for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
            if(ap.getListas_usuario_normal().get(i).getNombre().equals(nombre.getText())){
                for (int j = 0; j < ap.getListas_usuario_normal().get(i).getSolicitudes().size(); j++) {
                    
                        
//                        DefaultMutableTreeNode p=new DefaultMutableTreeNode(ima);
//                        
//                        n.add(p);
                        raiz.add(new DefaultMutableTreeNode(ap.getListas_usuario_normal().get(i).getSolicitudes().get(j)));
                        
          
                    
          
          arbol.setModel(new DefaultTreeModel(raiz));
          modelo_arbol.reload();
                }
            }
        }
   
            
        }
            
                   
            
             if(tab.getSelectedIndex()==3){
                 
                 
                 
            dtm3.setRowCount(0);
                for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
                    if(!ap.getListas_usuario_normal().get(i).equals(usuario_normal_actual)){
                        modelo3[0]=ap.getListas_usuario_normal().get(i);

                        dtm3.addRow(modelo3);

                     tabla_usuarios.setModel(dtm3);
                    }
                      
        }
              
                
                
            
    
             }
             
             
    }//GEN-LAST:event_tabStateChanged

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(menu_normal, "modifique");
         nombre.setEditable(true);
        correo.setEditable(true);
        new_fecha.setEnabled(true);
        usuarui1.setEditable(true);
        contraseña.setEditable(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        usuario_normal_actual.setNombre(nombre.getText());
       usuario_normal_actual.setCorreo(correo.getText());
       usuario_normal_actual.setFecha((Date)new_fecha.getValue());
       usuario_normal_actual.setUsuario(usuarui1.getText());
       usuario_normal_actual.setContraseña(contraseña.getText());
       
       JOptionPane.showMessageDialog(menu_normal, "usuario modificado");
       
       fecha.setText(new_fecha.getValue().toString());
        nombre.setEditable(false);
        correo.setEditable(false);
        new_fecha.setEnabled(false);
        usuarui1.setEditable(false);
        contraseña.setEditable(false);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
          admin_usuario_normal ap=new admin_usuario_normal("./usuario_normal.cbm");
        ap.cargarArchivo();
        for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
            if(ap.getListas_usuario_normal().get(i).getNombre().equals(nombre.getText())){
                
                ap.getListas_usuario_normal().remove(i);
                ap.escribirArchivo();
                menu_normal.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
       
        int z=tabla_usuarios.getSelectedRow();
        if(z>=0){
           

            admin_usuario_normal ap=new admin_usuario_normal("./usuario_normal.cbm");
            ap.cargarArchivo();
            ap.cargarArchivo();

            for (int i = 0; i < ap.getListas_usuario_normal().size(); i++) {
                if(ap.getListas_usuario_normal().get(i).getNombre().equals(nombre.getText())){
                    
                    for (int j = 0; j < ap.getListas_usuario_normal().size(); j++) {
                        if(j==z){
                            solicitudes sol=new solicitudes(ap.getListas_usuario_normal().get(i), ap.getListas_usuario_normal().get(j));
                            admin_solicitudes ad=new admin_solicitudes("./solicitudes");
                            ad.cargarArchivo();
                            ad.set_solicitud(sol);
                            ad.escribirArchivo();

                            ap.getListas_usuario_normal().get(j).setSolicitudes(sol);
                            ap.escribirArchivo();
                            JOptionPane.showMessageDialog(menu_administrador, "solicitud enviada a: "+ap.getListas_usuario_normal().get(j));
                        }
                    }

                    ap.escribirArchivo();

                }
            }
        }

    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        admin_usuario_normal ap=new admin_usuario_normal("./usuario_normal.cbm");
        ap.cargarArchivo();

//        DefaultComboBoxModel modelo=new DefaultComboBoxModel(
//            ap.getListas_usuario_normal().toArray());//toArray convierte de array a arreglo
//        cb_usuario_solicitud.setModel(modelo);

        DefaultTreeModel modelo_arbol=(DefaultTreeModel)arbol.getModel();
        DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modelo_arbol.getRoot();

        for (int a = 0; a < ap.getListas_usuario_normal().size(); a++) {
            if(ap.getListas_usuario_normal().get(a).equals(usuario_normal_actual)){
                for (int i = 0; i < ap.getListas_usuario_normal().get(a).getSolicitudes().size(); i++) {
                    solicitudes sol =ap.getListas_usuario_normal().get(a).getSolicitudes().get(i);
                    DefaultMutableTreeNode p=new DefaultMutableTreeNode(sol);

                    raiz.add(p);
                   
                    modelo_arbol.reload();
                }
            }
        }

    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog USUARIO;
    private javax.swing.JButton agregar_usuario;
    private javax.swing.JTree arbol;
    private javax.swing.JButton bloquear_normal;
    private javax.swing.JButton bloquear_publicaciones;
    private javax.swing.JRadioButton bt_abierto;
    private javax.swing.JRadioButton bt_amigos;
    private javax.swing.JRadioButton bt_cerrado;
    private javax.swing.JRadioButton bt_comentario;
    private javax.swing.JRadioButton bt_privado;
    private javax.swing.JRadioButton bt_problema;
    private javax.swing.JRadioButton bt_publico;
    private javax.swing.JRadioButton bt_repuestas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JList<String> jl_p;
    private javax.swing.JSpinner js_categoria;
    private javax.swing.JSpinner js_fecha;
    private javax.swing.JSpinner js_respuestas;
    private javax.swing.JLabel lb_imagen;
    private javax.swing.JDialog login;
    private javax.swing.JButton loging;
    private javax.swing.JDialog menu_administrador;
    private javax.swing.JDialog menu_normal;
    private javax.swing.JSpinner new_fecha;
    private javax.swing.JTextField nombre;
    private javax.swing.JRadioButton rb_usuario_admin;
    private javax.swing.JRadioButton rb_usuario_normal;
    private javax.swing.JTextArea ta_comentario;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    private javax.swing.JTable tabla_usuarios;
    private javax.swing.JTextArea tax2;
    private javax.swing.JTextArea texta;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_contraseña_login;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuario_login;
    private javax.swing.JTextField usuarui1;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuario> usuario=new ArrayList();
ArrayList<publicaciones> publicacion=new ArrayList();
usuario_normal usuario_normal_actual;
usuario_administrador usuario_admin_actual;

ArrayList<solicitudes> solicitud=new ArrayList();
}
